### ISSUE TITLE
Hi! ok!)

### ISSUE THREAD

**Issue by teftelexe** [ZXeRRinor/sharp_calculator#1]
Hello, we are looking for talented programmers. If you are interested, we will continue our communication.

**Comment by ZXeRRinor** [comment]
You have seen my education project on C#, but i have to warn you, that i'm
not C# programmer, my favourite language is Kotlin, secondary - Java and
Ruby (MRI and JRuby). That means, I have much more knowledge in the sphere
of JVM-languages, than in others.

**Comment by teftelexe** [comment]
How to contact you? Maybe we will offer cooperation in the future..

**Comment by ZXeRRinor** [comment]
You can write your letters to this email address. I check it regularly.

ср, 17 мар. 2021 г. в 20:24, Ilya ***@***.***>:
